### ISSUE TITLE
UI does not restore saved width/height

### ISSUE THREAD

**Issue by clangguth** [unibas-gravis/scalismo-ui#13]
The ScalismoFrame class has internal logic to save its position and size when it is closed, and to restore to these values when it is reopened, to take into account the user's preferences.

However, when instantiated via scalismo.ui.api.ScalismoUI (as is the default when using the high-level API or the ScalismoViewer app), this functionality is lost, because after initialization, the frame gets re-packed to whatever Java thinks is a good layout (not what I thought was a good layout when I last ran it ; -) ).

This only affects the size and position, not perspective, display scaling etc. (which do get restored as expected).

To fix this, the call to frame.pack() should be removed here: https://github.com/unibas-gravis/scalismo-ui/blob/master/src/main/scala/scalismo/ui/api/ScalismoUI.scala#L33

(sorry for not posting a full PR, but this is a trivial change)

**Comment by marcelluethi** [comment]
@clangguth thank you for reporting this and suggesting a fix. It should be fixed now.
