### ISSUE TITLE
Missing change of background color

### ISSUE THREAD

**Issue by madsendennis** [unibas-gravis/scalismo-ui#20]
It would be a handy feature to change the background colour of the panels. Especially white background for use when making screenshots for a paper or presentation.
The implementation could be done in different ways:
 - A colour palette window from the menu panel (in a pop-up window like the scaling window)
 - A colour palette in the Scene view
 - Button in the scene view to change the background colour between white and black.

**Comment by marcelluethi** [comment]
👍  This would be a really useful feature. As it is not used too often, I would prefer to have it in the menu. 
In Paraview it is even hidden somewhere in the control settings pane.

**Comment by madsendennis** [comment]
Issue solved with the pull request from @clangguth
