### ISSUE TITLE
Sidebar color pallet error when setting mesh to black

### ISSUE THREAD

**Issue by madsendennis** [unibas-gravis/scalismo-ui#22]
It is currently not possible to set the color value of a mesh/landmark/other to black within scalismo-ui. When doing so in code, this removes the option of further on changing the color value as shown in the attachment: 

![scalismoui_blackmeshbug](https://user-images.githubusercontent.com/12571611/38940603-d7265474-432a-11e8-9eeb-e931ea607251.png)

What would be the best way to solve this problem?
An additional color intensity bar?
Or, setting the color pallet to the standard colors even if black is chosen?

**Comment by clangguth** [comment]
Essentially, the solution is similar to what's done in the background color setting: you'll need an additional control over the brightness, while letting the color circle select hue and saturation. In other words, there are three dimensions, but one isn't currently controllable in the UI.

I'll take a look at this and come up with an integrated solution, maybe over the weekend.

**Comment by clangguth** [comment]
Fixed with #24
