### ISSUE TITLE
Impossible to change color of TetrahedralMesh3D

### ISSUE THREAD

**Issue by kahrpatrick** [unibas-gravis/scalismo-ui#43]
Visualization is not updated when picking a different color for a TetrahedralMesh3D.

![scalismoUI-screenshot](https://user-images.githubusercontent.com/18963412/69149476-d9b4b800-0ad6-11ea-9f8e-e30734a4b8a1.png)

**Comment by madsendennis** [comment]
Now fixed in the tetrahedralVisualisation branch from where the pull-request originates with commit: 649d7c6.

**Comment by madsendennis** [comment]
Fixed in PR #40 .
